#***welcome to numpy tutorial***

In [3]:
import numpy as np

In [2]:
myarr=np.array([[3,4,6,7,9], [4,6,45,34,8]],np.int32)

In [3]:
myarr[0,1]

np.int32(4)

In [4]:
myarr.shape

(2, 5)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
yourarr=np.array([2,34,5,6])

In [7]:
yourarr.dtype

dtype('int64')

In [1]:
print("saif")

saif


In [4]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [5]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
a3D.shape

(2, 2, 2)

In [7]:
a2D = np.array([[1, 2], [3, 4]])

In [8]:
a2D

array([[1, 2],
       [3, 4]])

In [9]:
a2D.shape

(2, 2)

In [10]:
a2D[1,1]

np.int64(4)

In [11]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [12]:
arr=np.array(x)

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [14]:
arr.sum(axis=0)

array([12,  8,  9])

In [15]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [16]:
arr.argmax()

np.int64(6)

In [17]:
arr.argmin()

np.int64(8)

In [20]:
arr.argsort(axis=0)

array([[2, 2, 0],
       [0, 0, 1],
       [1, 1, 2]])